### ISSUE TITLE
memory not freed

### ISSUE THREAD

**Issue by nikolaospanagopoulos** [nibblebits/PeachOS#10]
`  

    elf_file->elf_memory = kzalloc(stat.filesize);
    res = fread(elf_file->elf_memory, stat.filesize, 1, fd);
    if (res < 0)
    {
        goto out;
    }

    res = elf_process_loaded(elf_file);
    if(res < 0)
    {
        goto out;
    }
`

in elfloader.c file, in the elf_load function, we dont free the memory  we allocated with kzalloc,  if we fail to read the file or if we fail to load the file

**Comment by nibblebits** [comment]
We call elf_file_free so theres no issue anymore

Thanks
