### ISSUE TITLE
boot.asm and kernel.asm

### ISSUE THREAD

**Issue by JaihsonK** [nibblebits/PeachOS#11]
Hey!
There are a few problems with the code to switch to pmode:

1. we should turn on a20 line before switching to pmode
2. we set the segment registers in kernel.asm, but it should be done even before we call the data driver in boot.asm

sample code at [https://serpaeos.sourceforge.io/](url)

**Comment by nibblebits** [comment]
Taking a look at references from OSDEV.ORG I can confirm that switching A20 after protected mode is perfectly acceptable: https://wiki.osdev.org/A20_Line

We must be setting the segment registers in kernel.asm failure to do so is undefined behaviour. If you believe I am wrong please further clairfy points 1 and 2.

**Comment by nibblebits** [comment]
Update: It is possible that the loading succeeds because it is done at the hardware level, therefore bypassing the MMU(Memory managment unit) this would make sense why it would work even if the segment selectors are incorrectly setup.

**Comment by JaihsonK** [comment]
OK thanks for the update. Here is a wiki forum FYI [https://forum.osdev.org/viewtopic.php?f=1&t=56605&p=343733#p343733](url)

**Comment by nibblebits** [comment]
Hi
So just to confirm you solved this problem by loading the segment selectors in the bootloader rather than in kernel.asm right?

Are you booting on real hardware?
Thanks,
Dan

**Comment by JaihsonK** [comment]
Hey!
Yes, that is correct, the first thing under load32. 

I have not tried it on real hardware yet, I'm waiting for a PATA hard disk to come in the mail. However, I'm told that KVM maps very closely to real hardware (more than QEMU) and my OS works on KVM now that I made this adjustment.

**Comment by JaihsonK** [comment]
Thanks, you too!

**Comment by nibblebits** [comment]
Fixed: thank you you will see a commit shortly
