### ISSUE TITLE
fat16_load_fat_directory doesn't set starting sector

### ISSUE THREAD

**Issue by JaihsonK** [nibblebits/PeachOS#12]
We find the starting sector on line 540 (in PeachOS master), but we never set directory->starting_sector

**Comment by nibblebits** [comment]
Hello,
There is no bug, directory->starting_sector is not used at the master. Please ensure if you are not already to only be making bug reports for the master branch because some issues were fixed in video content

Thanks,d
Dan

**Comment by nibblebits** [comment]
If you do believe me to be mistaken please reopen with a deeper explanation with code from the master so it is clear
Thanks for reporting it nevertheless

Thanks,
Dan
