### ISSUE TITLE
fat16.c - incorrect value for last cluster in file

### ISSUE THREAD

**Issue by howardthuang** [nibblebits/PeachOS#22]
https://github.com/nibblebits/PeachOS/blob/master/src/fs/fat/fat16.c#L411:

`if (entry == 0xFF8 || entry == 0xFFF)`

This line is checking if the cluster entry is the last cluster in a file.  However, the value it is checking for is incorrect.  The EOC (end of chain) mark for FAT16 should be 0xFFF8 - 0xFFFF.

**Comment by nibblebits** [comment]
Thank you for fileing the issue report

**Comment by nibblebits** [comment]
Thanks howard that has now been fixed will issue a new commit shortly
