### ISSUE TITLE
gtk initialiazation falied :(

### ISSUE THREAD

**Issue by adligo** [nibblebits/PeachOS#25]
Hey Deniel, 

  After the running a simmilar command to install qemu-system-x86_64 on an Ubuntu Virtual Box install on Windows I get;
'gtk initialization falied'

  Please advise :)  Googling on my own and will update;
Scott

**Comment by adligo** [comment]
Both zlib.net and dragonzap.com have issues loading on the Firefox Browser on the Virtual Box.  However, I can load these from Windows just fine.   Dragonzap.com took a long time to load ...  hmm any clues here would be welcome :)

**Comment by nibblebits** [comment]
Hi,
You need to ensure your internet is configured correctly in virtual box, please find a youtube video on that 

Regarding " 'gtk initialization falied'" this implies your not using a GUI environment, please ensure you have a window system installed, it should come default in Ubuntu. However you cant use Ubuntu on winidows or your going to have problems, it must be within a virtual box instance or as your main OS.
Thanks
Dan

**Comment by adligo** [comment]
I'm using ubuntu from a Virtual Box session on Windows;
Most things seem to be working fine.
[gtk.png](https://github.com/adligo/pics.adligo.com/blob/main/gtk.png)

Please Advise & TIA,
Scott

**Comment by adligo** [comment]
FIXED, I was installing stuff as root as I hadn't setup the sudo file.  So in the terminal as root there was no GUI, but as the regular user there was.  Thanks for your comments!  Scott

**Comment by nibblebits** [comment]
Ahh great glad its working let me know if thiers any more trouble
Thanks
