### ISSUE TITLE
Bug in fat16_get_first_cluster

### ISSUE THREAD

**Issue by gierens** [nibblebits/PeachOS#29]
Correct me if I'm wrong but we are just ORing the high and low bits here:
https://github.com/nibblebits/PeachOS/blob/9518f7a15134c31d66a4efe5a67a8ffba67edf50/src/fs/fat/fat16.c#L355-L358

Shouldn't we shift the high bits like so:
```c
return (item->high_16_bits_first_cluster << 16) | item->low_16_bits_first_cluster;
```

**Comment by nibblebits** [comment]
Yes you are correct, this function by the end of the course does not get used anymore, it will be removed in a future lecture entirely

**Comment by nibblebits** [comment]
Thanks for mentioning the issue

**Comment by nibblebits** [comment]
Fixed: thanks for pointing that out I was mistaken earlier when i told you that it was removed at the end of the course.
You will see a commit shortly
Thanks again
