### ISSUE TITLE
GDB Breakpoint not working

### ISSUE THREAD

**Issue by MyPersonalGitAccount** [nibblebits/PeachOS#30]
To whom it may concern.

I hope you are doing well and are in good health.

Thank you for the great course content, I have been thoroughly enjoying it.

I am currently busy with this video in section 4: "21. Loading our 32 bit kernel into memory and working with debugging symbols" .

Up until now I believe I have followed the course correctly, I have re-watched this video multiple times.

After setting the break point on "_start", and running the "target remote | qemu....." then pressing c, the code runs without breaking. Has anyone else had this problem?

I did load the symbols at address "0x0100000" using the "add-symbol-file"
![BreakPoint](https://github.com/nibblebits/PeachOS/assets/20168888/85fbd1f2-44a6-41a4-86b7-6046fbaa6d6e)
 command.

**Comment by MyPersonalGitAccount** [comment]
I am using Pop_OS!

**Comment by nibblebits** [comment]
Hello,
Did you solve the problem yet? Have you attached debugging symbols to the correct address?  
Thanks
Dan

**Comment by nibblebits** [comment]
Please ask in Q&A
