### ISSUE TITLE
Checking if ELF file is executable is never done

### ISSUE THREAD

**Issue by fedi-nabli** [nibblebits/PeachOS#31]
In lecture 94, Implementing the ELF Loader - Part 2, we create the funciton `static bool elf_is_executable(struct elf_header* header)` since we are only working with executable files, but later at the video, when creating the `int elf_validate_loaded(struct elf_header* header)` function, we do not call it to validate the file format.

**Comment by nibblebits** [comment]
Fixed: thanks very much fedi you will see a commit shotly
