### ISSUE TITLE
Fat16 file system issue while seeking disk streamer

### ISSUE THREAD

**Issue by Manish5-9** [nibblebits/PeachOS#32]
The function in fat16.c "fat16_get_fat_entry" is responsible for getting  fat entry for cluster.
During this seek operation, it needs to set the position for disk streamer seek
This position was getting computed as fat_table_position * (cluster * PEACHOS_FAT16_FAT_ENTRY_SIZE
This needs to be fixed
So here we want to go from the position "fat_table_position" to these many bytes (cluster * PEACHOS_FAT16_FAT_ENTRY_SIZE)
so it should be
 diskstreamer_seek(stream, fat_table_position + (cluster * PEACHOS_FAT16_FAT_ENTRY_SIZE));

**Comment by nibblebits** [comment]
Fixed: Thanks very much you will see the commit shortly

**Comment by Manish5-9** [comment]
Thanks. Glad to know that the fix is committed

**Comment by nibblebits** [comment]
Cheers, theres also a new lecture on the course where we fix all the bugs incase your interested in fixing other things that people have reported, i go through them all, also changed the design slightly so its worth a watch. Or you can just check the most recent commit
